apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs-apps-frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vuejs-apps-frontend-deployment
  template:
    metadata:
      labels:
        app: vuejs-apps-frontend-deployment
    spec:
      containers:
        - name: vuejs-apps-frontend
          image: elghibaomar/vuejs-apps-frontend:latest
          env:
            - name: PORT
              value: "8082"
          ports:
          - containerPort: 8082


---
apiVersion: v1
kind: Service
metadata:
  name: vuejs-apps-frontend-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
  selector:
    app: vuejs-apps-frontend-deployment






